### ISSUE TITLE
Non-translatable strings in the news section and single post

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/wporg-parent-2021#121]
Strings that cannot be translated appear in the /news/ section of any locale.

- These two images are from the news section /news/:

![1](https://github.com/WordPress/wporg-main-2022/assets/83702259/24a9c847-2d48-4227-b5cb-36b2234bb4c8)
![2](https://github.com/WordPress/wporg-main-2022/assets/83702259/dc160450-720b-4d92-8b25-3c9b52f1c8e0)

- This image is an single post:

![3](https://github.com/WordPress/wporg-main-2022/assets/83702259/821874f6-075e-4738-a272-60159713b350)

**Comment by ryelle** [comment]
These pages are controlled by the parent theme (which is why I moved this issue). It looks like the parent theme's strings were not being imported into GlotPress. I've updated that, and made the other strings on News translatable, so those should show up soon.

I should have a fix for "By [author]" tomorrow.

**Comment by marcarmengou** [comment]
Thanks, the strings are already listed as translatable.

**Comment by ryelle** [comment]
Okay, I've added the `By %s` string so that the author prefix is translatable too. Everything here should be ready now.

The text inside the subscribe form comes from Jetpack though, so they'll need to be translated in the plugin project.

**Comment by marcarmengou** [comment]
Thank's @ryelle . Is it normal that the strings, already translated in GlotPress, still do not appear translated in all locale sites?

The strings in Jetpack's Subscribe block have been translated since August, in my locale, but they still appear in English. In fact, I see the same thing happening in all the locales.

**Comment by ryelle** [comment]
I'm not sure, maybe it has something to do with the strings coming from block attributes. It looks like we can pass in our own strings to the block, so that might be the simplest fix.

**Comment by marcarmengou** [comment]
Thanks @ryelle I think we can close this. The translated strings already appear in the locales /news/ and those of Jetpack's subscribe block as well.
