### ISSUE TITLE
Update node to latest supported version

### ISSUE THREAD

**Issue by mkismy** [WordPress/wporg-parent-2021#122]
The project currently [requires node v14](https://github.com/WordPress/wporg-parent-2021/blob/e702884737b001ff36cc97694cc7682dd38cddb9/.nvmrc) which support ended in April 2023. Can we update to the supported v20 or 18?

**Comment by ryelle** [comment]
Thanks for the issue! Initially we were on 14 to match with core & gutenberg, but they've [recently jumped to v20](https://make.wordpress.org/core/2023/12/20/updating-wordpress-to-use-more-modern-versions-of-node-js-npm-2/), so I think we should too.

**Comment by ryelle** [comment]
This was done for this project in https://github.com/WordPress/wporg-parent-2021/commit/f74a094ae5f7cdfa4466b37061be3ff955501e05.
