### ISSUE TITLE
404 svg not found

### ISSUE THREAD

**Issue by benniledl** [WordPress/wporg-parent-2021#126]
in the css file
`https://wordpress.org/showcase/wp-content/themes/wporg-parent-2021/build/style.css?ver=1709073776#`
search for `url(./images/quotemark.svg)`
this leads to following url:
`https://wordpress.org/showcase/wp-content/themes/wporg-parent-2021/build/images/quotemark.svg`
this url does not exist

original report on meta.trac: https://meta.trac.wordpress.org/ticket/7498

**Comment by dd32** [comment]
Copying comment from trac:

----
It looks like this is the rule:
https://github.com/WordPress/wporg-parent-2021/blob/00997d56a4852ac60c72b3c3c4019acd8519b96e/source/wp-content/themes/wporg-parent-2021/sass/blocks/_pullquote.scss#L5

It looks like it was copied from wporg-news-2021 without the image:

https://github.com/WordPress/wporg-news-2021/blob/e1d3bd54668c408ca19e0e007737892b2b747e5c/source/wp-content/themes/wporg-news-2021/sass/blocks/_pullquote.scss#L6

**Comment by ryelle** [comment]
The image was moved over, but the path was broken. Fixed in https://github.com/WordPress/wporg-parent-2021/commit/1bda3a0edc270c41f7d00187ac8090e710d9f475.
