### ISSUE TITLE
Add different color for visited links.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-parent-2021#128]
Reported: https://meta.trac.wordpress.org/ticket/7529

The new theme doesn't have a color for visited links. I don't see it in the [figma](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=1040%3A3521&mode=dev).

 @WordPress/meta-design

**Comment by jasmussen** [comment]
Is a classic purple color sufficient? If yes, I'd go with this one: #7a00df

**Comment by fcoveram** [comment]
Agree with @jasmussen

**Comment by macmanx2** [comment]
That'll work, thanks!

**Comment by adamwoodnz** [comment]
Adding this style to the parent does have wide ranging effects which will take some effort to override in undesirable places. See the screenshots on the [PR](https://github.com/WordPress/wporg-parent-2021/pull/129). I think we should consider whether this is what we want across the network. An alternative could be only applying it only on the Forums where there has been a user request.

**Comment by jasmussen** [comment]
I responded on the PR, that IMO the visited style should not be applied to navigation links (footer/header), CTAs (anything on the homepage) and other "evergreen" links (hero sections, callouts, headings). 

Is it possible to scope it only to sections that feature blue links on white text as a starting point? IMO that could mean applying it in blanket style across the entire Learn category as a starting point (Learn, Forums, Developer Resources, Documentation), and then expand from there as we learn how to best apply it?

**Comment by fcoveram** [comment]
Agree with @jasmussen. The plan proposed also sounds good to me if doable.
