### ISSUE TITLE
Chapter list overlaps content on Firefox

### ISSUE THREAD

**Issue by szepeviktor** [WordPress/wporg-parent-2021#167]
I use Firefox 115 on Windows.
Viewport width: 1283 px.
After scrolling down on this page
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#plugin-zip
Chapter list overlaps content.

![Image](https://github.com/user-attachments/assets/dfc22b4b-2b1a-498f-aca2-0726c43c00cc)

**Comment by szepeviktor** [comment]
I suspect a modern CSS feature.

**Comment by ryelle** [comment]
You're right that it's modern CSS — the space that should be there is applied by `:has()`, for which support starts in Firefox 121 (though [maybe you can enable](https://stackoverflow.com/questions/73936048/how-do-you-enable-has-selector-on-firefox) `layout.css.has-selector.enabled` to turn support on).

The browsers that are supported here are [the same as WordPress core](https://make.wordpress.org/core/handbook/best-practices/browser-support/). Firefox 115 isn't supported.

> Last 1 Android versions.
> Last 1 ChromeAndroid versions.
> Last 2 Chrome versions.
> Last 2 Firefox versions.
> Last 2 Safari versions.
> Last 2 iOS versions.
> Last 2 Edge versions.
> Last 2 Opera versions.
> Browsers with > 1% usage based on [can I use browser usage table](https://caniuse.com/usage-table)

**Comment by szepeviktor** [comment]
> Firefox 115 isn't supported.

That is a deeply sad fact.

**Comment by ronnyadsetts** [comment]
> You're right that it's modern CSS — the space that should be there is applied by `:has()`, for which support starts in Firefox 121 (though [maybe you can enable](https://stackoverflow.com/questions/73936048/how-do-you-enable-has-selector-on-firefox) `layout.css.has-selector.enabled` to turn support on).

Enabling layout.css.has-selector.enabled allows this to work in Firefox ESR 115 latest.

**Comment by szepeviktor** [comment]
Thank you.
