### ISSUE TITLE
Create a automatically generated build branch

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-parent-2021#5]
See https://github.com/WordPress/wporg-mu-plugins/pull/175

If we want to use this project in separate child-theme repos, it needs to have a branch with the built CSS files.

**Comment by ryelle** [comment]
Could we create a `build` branch that _only_ contains the parent theme at the root? Otherwise trying to install it via composer as a `wordpress-theme` will create a deeply nested theme in any project it's used in (probably something like `source/wp-content/themes/wporg-parent-2021/source/wp-content/theme/wporg-parent-2021`).

**Comment by dd32** [comment]
> Could we create a `build` branch that _only_ contains the parent theme at the root? 

That sounds like a good option to me.

Using `actions-js/push` (which is used in other repo's to push the entire repo to a branch) [you can just set the `directory` parameter](https://github.com/actions-js/push#:~:text=Directory%20to%20change%20to%20before%20pushing.) to push the content of a specific folder to the build branch instead.

**Comment by ryelle** [comment]
> Using actions-js/push (which is used in other repo's to push the entire repo to a branch) [you can just set the directory parameter](https://github.com/actions-js/push#:~:text=Directory%20to%20change%20to%20before%20pushing.) to push the content of a specific folder to the build branch instead.

Unfortunately that param doesn't seem to work that way, but I've got a (maybe hacky) method working with [some CLI commands](https://github.com/WordPress/wporg-parent-2021/blob/1e64d0ede552a39e6d1011c2b29071b458eb3f3d/.github/workflows/build.yml#L29-L44).

**Comment by dd32** [comment]
> Unfortunately that param doesn't seem to work that way

Yup :( It's actually for when you've checked out the Git repo into a subdirectory.. 

I've expanded upon your CLI commands to make it _just_ the theme files, which seemed to [work better on my own fork](https://github.com/dd32/wporg-parent-2021/tree/build).
