### ISSUE TITLE
Latest news: escaped HTML tags in news post-title

### ISSUE THREAD

**Issue by dionysous** [WordPress/wporg-parent-2021#51]
On the home page in the lower area, where the latest news are displayed, there are errors in the output of HTML within post titles. HTML tags are not removed, but escaped.

<img width="1616" alt="html-tags-not-removed" src="https://user-images.githubusercontent.com/12687777/198038276-f1611372-26b5-45e0-9096-3305bfc951c7.png" alt="Screenshot of the wordpress.org home page">

**Comment by ryelle** [comment]
Thanks for reporting this 🙂 

There shouldn't be HTML in post titles, so I've fixed that one title. If this happens again, or if HTML in post titles is intentional, we could look at supporting that. For now, fixing the title itself is better.
