### ISSUE TITLE
Smaller block spacing size option needed for 

### ISSUE THREAD

**Issue by justintadlock** [WordPress/wporg-parent-2021#57]
We could use something between the `0` spacing size and the `Custom (0.5rem)` size for spacing in the Row block for post meta so that `By Date in Categories` reads more naturally.  Just needs to be a tiny bit narrower.

Another option might be enabling custom spacing sizes in the `theme.json` for these situations:

<img width="1296" alt="block-spacing-small" src="https://user-images.githubusercontent.com/1816309/202809442-ef7d0d1d-1de4-4352-94a4-3111b9962221.png">

This is made up of a Row block that wraps `Paragraph + Post Date + Paragraph + Categories`.

I tried adding before/after spaces in the Paragraph blocks themselves, but the editor trims them.

**Comment by ryelle** [comment]
I've also run into some issues where having custom spacing would be ideal, so let's enable that in the parent theme for all the new-design sites. It's set here: https://github.com/WordPress/wporg-parent-2021/blob/5f0332a796b33f43ae568476e935ad145d02514e/source/wp-content/themes/wporg-parent-2021/theme.json#L463
