### ISSUE TITLE
Consider hiding admin bar for most pages

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-parent-2021#59]
> The adminbar seems useful mainly to contributors, which is likely a very small percentage of visitors. Can we hide the adminbar on virtually every page, unless you're logged in? Perhaps keep it mainly for the Make sites?

I think this should ultimately be a ticket in meta since it's a significant change. Leaving this ticket open here for now.

**Comment by jasmussen** [comment]
There may be overlap between this and https://github.com/WordPress/wporg-mu-plugins/issues/252#issuecomment-1317936213

**Comment by tellyworth** [comment]
Yes that 252 issue is exactly the reason for this one. It's easy enough to enable or disable the admin bar wherever it's needed, we just need a decision as to where it's appropriate and where not. @jasmussen is that a design consideration or should we make the decision based on whatever a public ticket suggests?

**Comment by jasmussen** [comment]
> is that a design consideration or should we make the decision based on whatever a public ticket suggests?

For now, I would think it urgent to just go back to what used to work for Otto in the past. But based on a broader conversation (I'm genuinely a bit out of my depth here), I would merely submit as a personal opinion, that the fewer places we show the adminbar, the better.

**Comment by ryelle** [comment]
Why was this created as a separate issue from https://github.com/WordPress/wporg-mu-plugins/issues/252, and in the parent theme repo? I'm only asking in the interest of not fragmenting conversation further, as the admin bar change would happen in wporg-mu-plugins. Or is there a parent-theme specific change that needs to happen in response to an admin bar change?

**Comment by StevenDufresne** [comment]
It was just a placeholder, I was unaware that there was an open ticket. Let's continue the conversation in !https://github.com/WordPress/wporg-mu-plugins/issues/252. I don't think anything has been said here that needs to be moved over. If so, feel free to repost.
