### ISSUE TITLE
↗︎ emoji is very similar to "external link" and "opens in new tab" icons

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-parent-2021#64]
![Screenshot 2022-12-09 at 2 44 54 PM](https://user-images.githubusercontent.com/484068/206807666-efcba171-d448-4447-a798-49d310665c12.png)

When I saw the ↗︎ emoji in that link, I assumed it was being used to indicate that the link opens in a new tab or was an external site, because of how similar it is to the [the icons that are commonly used](https://www.google.com/search?q=new+tab+icon&tbm=isch) for that purpose. It seems to me like the upwards arrow is the substantive part that communicates an "exit" from the site/tab, and the surrounding box is decorative.

@shaunandrews and @jasmussen mentioned that ↗︎ was only meant to be decorative, though. I wonder if we should consider a different emoji for that purpose, to avoid confusion?

**Comment by jasmussen** [comment]
Thanks for the issue, good to look at holistically! And CC: @beafialho @pablohoneyhoney as I think they were involved in some of the initial design.

My understanding of this is that these unicode glyphs are indeed entirely decorative elements that are applied in some contexts and on some links as part of the design language. I think they look good, personally, and appreciate the flourish.

I don't know if we need to denote external links with a separate icon, but if we do, we have an icon for this purpose:

<img width="387" alt="Screenshot 2022-12-12 at 10 39 36" src="https://user-images.githubusercontent.com/1204802/207012575-5cc035d5-bfee-44c4-b13d-d71513c53674.png">

— that's used for external links in the block editor, though in general it's sized down 50% to be 12x12px.

As for links that open in a new tab, I would personally prefer we avoid these across the site, for any reason, and whenever that is applied it's an exception to the rule.

None of the above are strong opinions. I could also be fine with a replacement glyph, or no glyph at all. However I would love to hear a little more background before we make such a change.

**Comment by beafialho** [comment]
> these unicode glyphs are indeed entirely decorative elements that are applied in some contexts and on some links as part of the design language. I think they look good, personally, and appreciate the flourish.

This understanding is correct, these are a decorative option part of the design language. I appreciate the detail of them being there, especially where they contribute to the visual aspect of [specific patterns](https://cloudup.com/cJsUZHV31oO). Of course, If that causes confusion, we can opt to only add them to external links or new tab links.

If, however, in a pattern like the screenshot I shared above, we were to have both internal and external links, we should just not use these glyphs at all, as it would look inconsistent.

**Comment by StevenDufresne** [comment]
Adding, I made the same observation (and missed this ticket) when implementing a change in [wporg-showcase](https://github.com/WordPress/wporg-showcase-2022/pull/110).

https://github.com/WordPress/wporg-showcase-2022/pull/110#issuecomment-1353874722.

**Comment by jasmussen** [comment]
To move this forward, yes let's converge on the up/right Unicode character, in place of the icon, across all of wp.org. It seems to work well!
