### ISSUE TITLE
Heading 'Link & Arrow' style doesn't support RTL

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-parent-2021#68]
The Link and Arrow style used on the w.org [homepage](https://wordpress.org), [showcase](https://wordpress.org/showcase/) and [enterprise](https://wordpress.org/enterprise-2/) pages (and maybe others) doesn't support RTL reading direction:

Home
![Screen Shot 2023-01-13 at 4 16 37 PM](https://user-images.githubusercontent.com/1017872/212229577-1271a7d0-c5c6-483f-9309-4daa439154c1.jpg)

Enterprise
![Screen Shot 2023-01-13 at 4 11 19 PM](https://user-images.githubusercontent.com/1017872/212229598-35413670-be32-4e2d-a008-e8285328c17b.jpg)

Showcase
![Screen Shot 2023-01-13 at 4 20 52 PM](https://user-images.githubusercontent.com/1017872/212229701-8abea122-78d7-4f35-9ff3-8112c668d8cb.jpg)

### Steps to repro

1. Open any of these pages
2. Add attribute `dir="rtl"` to the HTML element
3. Scroll to the bottom of the page and observe that the arrow is pointing the wrong way, and when hovering it also moves in the wrong direction

**Comment by ryelle** [comment]
It looks like this was fixed at some point: https://ar.wordpress.org/?new-theme=1

<img width="1340" alt="Screenshot 2024-01-18 at 11 50 21 AM" src="https://github.com/WordPress/wporg-parent-2021/assets/541093/746b5f8c-6221-4c86-b26d-69e9e4691414">
