### ISSUE TITLE
Archive vs Category Template? missing title / term description

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-parent-2021#8]
Question: What's the difference between an Archive template and a Category template
<img width="350" alt="Screen Shot 2022-05-25 at 15 11 00" src="https://user-images.githubusercontent.com/39980/170282932-445395bc-dc5c-4408-b24d-598bb827f867.png">
?

Wouldn't Category template be redundant?

**Comment by bph** [comment]
And should we create one or would you want to provide a generic one. We can certainly expand on that but the current category pages don't show a post title or term description. 
https://developer.wordpress.org/test-site-test/category/beginners/

**Comment by ryelle** [comment]
Archive is used for category pages if there is no category template (and same for tag, date, etc).

I'll add the templates & let you check them out.
