### ISSUE TITLE
Subnav mobile state looks broken.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-parent-2021#85]
When viewing https://wordpress.org/documentation/ on mobile,the subnav menu is misaligned.

## Screenshot
<img width="483" alt="Screenshot 2023-05-03 at 8 44 10 PM" src="https://user-images.githubusercontent.com/1657336/235906963-b3d0c961-8366-4156-b22e-02d0ba95a640.png">

## How to test
1. Visit https://wordpress.org/documentation on a mobile device
2. Expand the subnav
3. Notice the menu overlaps oddly.

**Comment by ryelle** [comment]
According to [this report,](https://meta.trac.wordpress.org/ticket/7011) it also happens on the About subpages: 
![CleanShot 2023-05-25 at 16 18 35](https://github.com/WordPress/wporg-parent-2021/assets/541093/3709ea3d-dc24-49f6-9fcb-36aa5b2d74ec)
